[package]
name = "maze_game"
version = "0.1.0"
authors = ["Cory Tertel <demeaningframe0@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"